title: Grigoriy Ovchinnikov | Data Scientist & ML Engineer
logo: /assets/img/profile.png
description: Personal portfolio site of Grigoriy Ovchinnikov | Data Scientist & ML Engineer.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
